# Banco de dados Neon (produção)
spring.datasource.url=jdbc:postgresql://ep-tiny-dream-ac265hiq.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Porta
server.port=8080